{
 "title": "project",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Average Latency (Daily)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start,1d),\n  avg(time_to_first_byte) AS \"Average Daily Latency\"\nFROM \"tor-statistics\".\"onionperf_data\"\nWHERE\n  $__timeFilter(start)\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start,1d),\n  stddev(time_to_first_byte) AS \"Standard Deviation\"\nFROM \"tor-statistics\".\"onionperf_data\"\nWHERE\n  $__timeFilter(start)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Number of Users In Global Tor Network",
   "type": "timeseries",
   "description": "Estimated Number of Users in the Tor Network",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  user_estimate AS metric,\n  user_estimate,\n  country_id\nFROM \"tor-statistics\".\"user_statistics\"\nWHERE\n  $__timeFilter(date) AND\n  \"tor-statistics\".\"user_statistics\".country_id = 'Total'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Average Latency and Transfer Speed (Every 6 hours)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start,6h),\n  avg(time_to_first_byte) AS \"Average Latency\"\nFROM \"tor-statistics\".\"onionperf_data\"\nWHERE\n  $__timeFilter(start)\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start,6h),\n  avg(mbps) AS \"Average Network Speed\"\nFROM \"tor-statistics\".\"onionperf_data\"\nWHERE\n  $__timeFilter(start)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Percentage of IPv6 supporting Relays/Bridges",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  announced_ipv6_relays/avg_relays \"Percentage of IPv6 Supporting Relays\",\n  announced_ipv6_bridges/avg_bridges \"Percentage of IPv6 Supporting Bridges\"\nFROM \"tor-statistics\".\"relays_and_bridges\"\nWHERE\n  $__timeFilter(date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Percentage of Errors during statistics gathering",
   "type": "timeseries",
   "description": "Error Percentage from OnionPerf",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  server_origin AS metric,\n  number_of_failures/number_of_measurements \"Percentage of Errors in Statistics Gathering\"\nFROM \"tor-statistics\".\"onionperf_daily_additional\"\nWHERE\n  $__timeFilter(date)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Relay Number By Operating System",
   "type": "timeseries",
   "description": "Relay Number By Operating System in Global Tor Network",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  avg(bsd) AS \"bsd\",\n  avg(linux) AS \"linux\",\n  avg(macos) AS \"macos\",\n  avg(other) AS \"other\",\n  avg(windows) AS \"windows\"\nFROM \"tor-statistics\".\"relays_and_bridges\"\nWHERE\n  $__timeFilter(date)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Number of Relays Actually Reachable from Avg Amount of Declared",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  reachable_ipv6_relays/avg_relays AS metric\nFROM \"tor-statistics\".\"relays_and_bridges\"\nWHERE\n  $__timeFilter(date)\nORDER BY 1,2"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } }
 ]
}